version: "3"

services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/app

  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: docker
      MYSQL_ROOT_PASSWORD: secret

  composer:
    image: composer/composer
    command: composer install
    volumes:
      - ./:/app
